config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#home'
  get 'resources', to: 'places#resources'
  resources :places, only: [:index]
  resources :helpers
  resources :helpees
  resources :messages, only: [:index, :create, :destroy]
  resources :conversations do
    resources :direct_messages
  end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create :send_to_firebase
  belongs_to :user

  def send_to_firebase
    FIREBASE.push("message", { :id => self.id, :body => self.body, :'.priority' => 1, :timestamp => self.created_at })
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  after_filter :destroy_message

  def index
    if current_user.helpee.present? || current_user.helper.present?
      @message = Message.new
      @messages = Message.includes(:user).order(:id).all
    else 
      return render plain: 'You need to create a profile first.', status: :forbidden
    end
  end

  def create
    if current_user.helpee.present? || current_user.helper.present?
      Message.create(message_params.merge({user_id: current_user.id, email: current_user.email}))
      redirect_to messages_path
    else
      return render plain: 'You need to create a profile first.', status: :forbidden
    end
  end

  def destroy
  end

  private

  def destroy_message
    @messages = Message.order(:id).all
    if @messages.length > 12
      @messages[0].destroy
    end
  end

  def message_params
    params.require(:message).permit(:body)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<br />
<h1 class="underline-words text-center">Chat Room</h1>
<br />

<div class="booyah-box col-10 offset-1">
  <% @messages.each do |message| %>
  
    <div class="row">
      <div class="float-left">
        <% user = message.user %>
        <% if user.helpee.present? %>
          <% if user.helpee.avatar.present? %>
            <%= image_tag user.helpee.avatar, class: "chat-pic" %>
          <% else %>
            <%= image_tag "fillerProfile.jpg", class: "chat-pic" %>
          <% end %>
        
        <% elsif user.helper.present? %>
          <% if user.helper.avatar.present? %>
            <%= image_tag user.helper.avatar, class: "chat-pic" %>
          <% else %>
            <%= image_tag "fillerProfile.jpg", class: "chat-pic" %>
          <% end %>
        <% else %>
          <%= image_tag "fillerProfile.jpg", class: "chat-pic" %>
        <% end %>
      </div>
      <div class="text-left">
        <% if current_user.id != message.user_id %>
          <strong class="inline-space on-hover clicked-name" data-user-id="<%= message.user_id %>">
            <% if user.helpee.present? %>
              <%= user.helpee.name %>
            <% end %>
            <% if user.helper.present? %>
              <%= user.helper.name %>
            <% end %>
          </strong>
          <strong class="inline-space filler-left">
          <% if !(user.helpee.present?) && !(user.helper.present?) %>
            Profile-Deleted
          <% end %>
          </strong>

        <% else %>
          <strong class="inline-space">
          <% if user.helpee.present? %>
            <%= user.helpee.name %>
          <% end %>
          <% if user.helper.present? %>
            <%= user.helper.name %>
          <% end %>
          </strong>
        <% end %>
        <%= message.created_at.strftime("%B %e, %Y at %I:%M %p") %>
        <br />
        <%= message.body %>
        <div class="clearing"></div>
      </div>
    </div>
  
    <div class="modal fade <%= "myModal-#{message.user_id}" %> modalOpen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header1">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <% id = message.user_id %>
            <% user = User.find(id) %>
            <% if user.helpee.present? %>
              <h4 id="h4Id"><%= user.helpee.name %></h4>
            <% end %>
            <% if user.helper.present? %>
              <h4 id="h4Id"><%= user.helper.name %></h4>
            <% end %>
          </div>
      
          <div class="modal-body">
            <div>
              <% if user.helpee.present? %>
                <% if user.helpee.avatar.present? %>
                  <%= image_tag user.helpee.avatar, class: "resize-filler" %>
                <% else %>
                  <%= image_tag "fillerProfile.jpg", class: "resize-filler" %>
                <% end %>
              <% end %>
              <% if user.helper.present? %>
                <% if user.helper.avatar.present? %>
                  <%= image_tag user.helper.avatar, class: "resize-filler" %>
                <% else %>
                  <%= image_tag "fillerProfile.jpg", class: "resize-filler" %>
                <% end %>
              <% end %>
            </div>
            
            <div class="text-center">
              <%= link_to "Send Direct Message", conversations_path(sender_id: current_user.id, 
              recipient_id: message.user_id), method: 'post' %>
              <br />
              <% if user.helpee.present? %>
                <%= link_to "See #{user.helpee.name}'s Profile", helpee_path(user.helpee.id) %>
              <% end %>
              <% if user.helper.present? %>
                <%= link_to "See #{user.helper.name}'s Profile", helper_path(user.helper.id) %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<hr class="col-10 offset-1" />

<div class="col-10 offset-1 text-insert" >
  <%= simple_form_for @message do |f| %>
    <%= f.input :body, input_html: {id: "workdamnit"} %>
    <%= f.submit "Chat!", class: "btn btn-primary" %>
  <% end %>
</div>
<br />
<br />

<script type="text/javascript">
  var clicked = $(".clicked-name")
  clicked.click(function(data) {
    userId = data.currentTarget.getAttribute('data-user-id');
    console.log(userId);
    $('.myModal-' + userId).first().modal('toggle');
  })
</script>

<script src="https://www.gstatic.com/firebasejs/4.9.1/firebase.js"></script>
<script>
  // $('#myform').children('input').val('')
  // $('#myform').find('input').val('')
  // $("#myform")[0].val('');
  // $("#myform").reset();
  // $('#myForm').trigger("reset")
  // document.onload = function() {  
  // document.getElementById("input-focus").focus();
  // }
  $('#workdamnit').val('');
  $('#workdamnit').focus();

  var lastMessagePageShown = <%= Message.order(:id).last.to_json.html_safe %>;
  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyBOl_hMGb_qqY5jnZsALk9Z2_H4hiaCTY8",
    authDomain: "passion-chat.firebaseapp.com",
    databaseURL: "https://passion-chat.firebaseio.com",
    projectId: "passion-chat",
    storageBucket: "passion-chat.appspot.com",
    messagingSenderId: "501201445940"
  };
  firebase.initializeApp(config);

  var database = firebase.database();

  var messageRef = database.ref('message');
  console.log(messageRef);
  messageRef.on('value', function(snapshot) {
    // updateStarCount(postElement, snapshot.val());
    // console.log(snapshot.val());
    var values = snapshot.val();
    var ids = Object.keys(values);
    var lastId = ids[ids.length - 1];
    var lastMessage = values[lastId];
    console.log(lastMessage);
    if(lastMessagePageShown.id < lastMessage.id) {
      location.reload();
    }
  });
</script>