config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#home'
  get 'resources', to: 'places#resources'
  resources :places, only: [:index]
  resources :helpers
  resources :helpees
  resources :messages, only: [:index, :create, :destroy]
  resources :conversations do
    resources :direct_messages
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :direct_messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  # Query database to find a conversation that already exists
  # This is a class level method which is equivalent to the commented out def below.
  # Class level method is a method that can be called on the class itself.
  scope :between, -> (sender_id,recipient_id) do
    # Prevents SQL injection.  Sanitizes code
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR
      (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  def unread
    direct_messages.where("user_id = ? AND read = false", recipient_id).count
  end

  # Results of trial and error. Class level method:
  # def self.between(sender_id, recipient_id)
  # end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  after_filter :destroy_conversation

  def index
    if current_user.helpee.present? || current_user.helper.present?
      @users = User.all
      @conversations = Conversation.all
    else
      return render plain: 'You need to create a profile first.', status: :forbidden
    end
  end

  def update
    @conversation = Conversation.find(params[:id])
    @message = @conversation.direct_messages.where(recipient_id: current_user.id)
    @message.update_all(read: true)
    # @conversation.direct_messages.update_all(read: true)
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_direct_messages_path(@conversation)
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.destroy
    redirect_to conversations_path
  end

  private

  def destroy_conversation
    @conversations = Conversation.all
  end

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class="booyah-box col-10 offset-1">
 <h3 class="mailbox">Mailbox</h3>
 <div>
  <div class="line-height">
   <% @conversations.each do |conversation| %>
   <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
    <% if conversation.sender_id == current_user.id %>
      <% recipient = User.find(conversation.recipient_id) %>
      
    <% else %>
      <% recipient = User.find(conversation.sender_id) %>
    <% end %>

    <div class="row">
      <div class="float-left">
        <% if recipient.helpee.present? %>
          <% if recipient.helpee.avatar.present? %>
            <%= image_tag recipient.helpee.avatar, class: "chat-pic convo-pic" %>
          <% else %>
            <%= image_tag "fillerProfile.jpg", class: "chat-pic convo-pic" %>
          <% end %>
        <% elsif recipient.helper.present? %>
          <% if recipient.helper.avatar.present? %>
            <%= image_tag recipient.helper.avatar, class: "chat-pic convo-pic" %>
          <% else %>
            <%= image_tag "fillerProfile.jpg", class: "chat-pic convo-pic" %>
          <% end %>
        <% else %>
          <%= image_tag "fillerProfile.jpg", class: "chat-pic convo-pic" %>
        <% end %>
      </div>
      <div class="text-left conversation-text">
        <strong class="inline-space">
          <% if recipient.helpee.present? %>
            <%= link_to recipient.helpee.name, conversation_direct_messages_path(conversation)  %>
          <% end %>
          <% if recipient.helper.present? %>
            <%= link_to recipient.helper.name, conversation_direct_messages_path(conversation)  %>
          <% end %>
        </strong>
        <strong class="inline-space filler-left">
          <% if !(recipient.helpee.present?) && !(recipient.helper.present?) %>
            <%= link_to "Profile Deleted", conversation_direct_messages_path(conversation)  %>
          <% end %>
        </strong>
      
        &nbsp<%= current_user.all_unread_conversation_messages(conversation) %> <span>Unread Messages</span>&nbsp
        <%= link_to 'Delete Conversation', conversation_path(conversation), method: :delete, data: 
        {confirm: 'Are you sure you want to delete this conversation?'}, class: "add-height" %>
      </div>
    </div>
    <br />
   <% end %>
  <% end %>
  </div>
 </div>
</div>

<div class="booyah-box col-10 offset-1">
  <h3 class="mailbox">All Users</h3>
  <div>
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <% if user.helper || user.helpee %>
          <div class="row">
            <div class="float-left">
              <% if user.helpee.present? %>
                <% if user.helpee.avatar.present? %>
                  <%= image_tag user.helpee.avatar, class: "chat-pic convo-pic user-pic" %>
                <% else %>
                  <%= image_tag "fillerProfile.jpg", class: "chat-pic convo-pic user-pic" %>
                <% end %>
              <% end %>
              <% if user.helper.present? %>
                <% if user.helper.avatar.present? %>
                  <%= image_tag user.helper.avatar, class: "chat-pic convo-pic user-pic" %>
                <% else %>
                  <%= image_tag "fillerProfile.jpg", class: "chat-pic convo-pic user-pic" %>
                <% end %>
              <% end %>
            </div>

            <div class="text-left user-text">
              <% if user.helpee.present? %>
                <strong class="inline-space">
                  <%= link_to user.helpee.name, helpee_path(user.helpee) %>
                </strong> 
                &nbsp 
                <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
              <% end %>
              <% if user.helper.present? %>
                <strong class="inline-space">
                  <%= link_to user.helper.name, helper_path(user.helper) %> 
                </strong>
                &nbsp 
                <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>