config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#home'
  get 'resources', to: 'places#resources'
  resources :places, only: [:index]
  resources :helpers
  resources :helpees
  resources :messages, only: [:index, :create, :destroy]
  resources :conversations do
    resources :direct_messages
  end
end

app/models/helpee.rb
class Helpee < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true, length: { minimum: 3 }, uniqueness: true
end

app/controllers/helpees_controller.rb
class HelpeesController < ApplicationController
  before_action :authenticate_user!

  def index
    @helpee = Helpee.all
  end

  def new
    if current_user.helper.present?
      return render plain: 'You already have a helper profile', status: :forbidden
    end

    if current_user.helpee.present?
      return render plain: 'You already have a helpee profile', status: :forbidden
    end
    @helpee = Helpee.new
  end

  def show
    @helpee = Helpee.find(params[:id])
  end

  def edit
    @helpee = Helpee.find(params[:id])

    if @helpee.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @helpee = Helpee.find(params[:id])

    if @helpee.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @helpee.update_attributes(helpee_params)
    
    if @helpee.valid?
      redirect_to helpee_path(@helpee)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @helpee = Helpee.find(params[:id])

    if @helpee.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @helpee.destroy
    redirect_to root_path
  end

  def create
    @user = current_user
    @helpee = Helpee.new(helpee_params)
    @helpee.user = @user
    @helpee.save

    if @helpee.valid?
      redirect_to places_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def helpee_params
    params.require(:helpee).permit(:name, :about, :story, :need, :address, :avatar, :notifications)
  end
end

app/helpers/helpees_helper.rb
module HelpeesHelper
end

app/views/helpees/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Profile</h1>
  <%= simple_form_for @helpee do |f| %>
    <%= f.input :name %>
    <%= f.input :about %>
    <%= f.input :story %>
    <%= f.input :need %>
    <%= f.input :address %>
    <%= f.input :avatar %>
    <%= f.input :notifications, as: :boolean, checked_value: true, unchecked_value: false, label: 'Receive email notifications?' %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/helpees/index.html.erb
<h1>helpee index</h1>

app/views/helpees/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Tell Us About You</h1>
  <h5>The only thing you need to create an account is your name.  
  All other fields can be left blank.  You can update your profile with more information at any time.</h5>
  <%= simple_form_for @helpee do |f| %>
    <%= f.input :name %>
    <%= f.input :about %>
    <%= f.input :story %>
    <%= f.input :need %>
    <%= f.input :address %>
    <%= f.input :avatar %>
    <%= f.input :notifications, as: :boolean, checked_value: true, unchecked_value: false, label: 'Receive email notifications?' %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/helpees/show.html.erb
<div class="booyah-box col-10 offset-1 taller">
  <% if @helpee.avatar.present? %>
    <%= image_tag @helpee.avatar, class: "left" %>
  <% else %>
    <%= image_tag "fillerProfile.jpg", class: "left resize-filler1" %>
  <% end %>

  <h1><%= @helpee.name %></h1>
  <% if current_user && current_user == @helpee.user %>
    <%= link_to 'Inbox', conversations_path, class: 'btn btn-primary right button-top reposition-button' %>
  <% end %>
  <br />
    
  
  <h3 class="underline-words">About Me</h3>
  <p><%= @helpee.about %></p>

  <h3 class="underline-words">What's my story?</h3>
  <p><%= @helpee.story %></p>
  <h3 class="underline-words">What I need</h3>
  <p><%= @helpee.need %></p>
  

  <% if current_user != @helpee.user %>
    <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: @helpee.user_id), 
    method: 'post', class: "btn btn-primary float-left buttons-right" %>
  <% end %>

  <div class="float-right buttons-right">
    <% if current_user && current_user == @helpee.user %>
      <%= link_to 'Edit Profile', edit_helpee_path(@helpee), class: 'btn btn-primary' %>
      <%= link_to 'Delete Profile', helpee_path(@helpee), method: :delete, data: 
      {confirm: 'Are you sure you want to delete your profile?'}, class: 'btn btn-danger' %>
    <% end %>
  </div>
  <br />
</div>

<br />

<% if @helpee.latitude.present? && @helpee.longitude.present? %>
  <script>
    function initMap() {
      var myLatLng = {lat: <%= @helpee.latitude %>, lng: <%= @helpee.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Come find me'
      });
    }
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwy0zq-PsBe_jtUVPkba-Jkm09YsXXvmg&callback=initMap">
  </script>

  <br />
  <br />
  <br />
  <div class="text-center">
    <h3>Where you may be able to find me</h3>
    <br />
  </div>
  <div id="map"></div>
<% end %>