config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#home'
  get 'resources', to: 'places#resources'
  resources :places, only: [:index]
  resources :helpers
  resources :helpees
  resources :messages, only: [:index, :create, :destroy]
  resources :conversations do
    resources :direct_messages
  end
end

app/models/place.rb
class Place < ApplicationRecord
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def home
    @helper = Helper.all
    @helpee = Helpee.all
  end

  def index
    @helper = Helper.all
    @helpee = Helpee.all
  end

  def resources
  end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/home.html.erb
<div id="Slogan">
  <button type="button" class="btn btn-primary btn-lg float-right img-button" data-toggle="modal" data-target="#myModal">
    Add A Profile
  </button>

  <h1>
    <div id="banner1" class="banner">
      <h2 class = "carousel-caption testing">
        "God will take care of the poor trampled slave, 
          but where will the slaveholder be when eternity begins?" - Sojourner Truth
      </h2>
    </div>
    <div id="banner2" class="banner">
      <h2 class = "carousel-caption testing">
        "You can easily judge the character of a man by how he treats those who can do nothing for him." - Malcolm S. Forbes
      </h2>
    </div>
    <div id="banner3" class="banner">
      <h2 class = "carousel-caption testing">
        Ezekiel 16:49 "Behold, this was the guilt of your sister Sodom: she and her daughters had pride, 
        excess of food, and prosperous ease, but did not aid the poor and needy."
      </h2>
    </div>
    <div id="banner4" class="banner">
      <h2 class = "carousel-caption testing">
        Yom Kippur Haftarah: Isaiah 58:7 "It is to share your bread with the hungry, and to take the wretched poor into your home.  When you see the naked, to clothe him, and not to ignore your own kin."
      </h2>
    </div>
    <div id="banner5" class="banner">
      <h2 class = "carousel-caption testing">
        Yom Kippur Haftarah: Isaiah 58:10 "If you banish the yoke from your midst, the menacing hand, and evil speech, 
        and you offer your compassion to the hungry and satisfy the famished creature, then shall your light shine in darkness, 
        and your gloom shall be like noonday."
      </h2>
    </div>
    <div id="banner6" class="banner">
      <h2 class = "carousel-caption testing">
        "Have compassion for all beings, rich and poor alike; each has their suffering. Some suffer too much, others too little." - Buddha
      </h2>
    </div>
    <div id="banner7" class="banner">
      <h2 class = "carousel-caption testing">
        "Where justice is denied, where poverty is enforced, where ignorance prevails, and where any one class is made to feel that society is an organized conspiracy to oppress, rob and degrade them, neither persons nor property will be safe." - Frederick Douglass
      </h2>
    </div>
    <div id="banner8" class="banner">
      <h2 class = "carousel-caption testing">
        "Poverty is the worst form of violence." - Mahatma Gandhi
      </h2>
    </div>
    <div id="banner9" class="banner">
      <h2 class = "carousel-caption testing">
        "Being unwanted, unloved, uncared for, forgotten by everybody, I think that is a much greater hunger, 
        a much greater poverty than the person who has nothing to eat." - Mother Teresa
      </h2>
    </div>
    <div id="banner10" class="banner">
      <h2 class = "carousel-caption testing">
        "A business that makes nothing but money is a poor business." - Henry Ford
      </h2>
    </div>
    <div id="banner11" class="banner">
      <h2 class = "carousel-caption testing">
        "Let us touch the dying, the poor, the lonely and the unwanted according to the graces we have received and let us not be ashamed or slow to do the humble work." - Mother Teresa
      </h2>
    </div>
    <div id="banner12" class="banner">
      <h2 class = "carousel-caption testing">
        "What does love look like? It has the hands to help others. It has the feet to hasten to the poor and needy. It has eyes to see misery and want. It has the ears to hear the sighs and sorrows of men. That is what love looks like." - Saint Augustine
      </h2>
    </div>
    <div id="banner13" class="banner">
      <h2 class = "carousel-caption testing">
        Proverbs 14:31 "Whoever oppresses a poor man insults his Maker, but he who is generous to the needy honors him."
      </h2>
    </div>
    <div id="banner14" class="banner">
      <h2 class = "carousel-caption testing">
        "If the misery of the poor be caused not by the laws of nature, but by our institutions, great is our sin." - Charles Darwin
      </h2>
    </div>
    <div id="banner15" class="banner">
      <h2 class = "carousel-caption testing">
        "Foxes have dens and birds have nests, but the Son of Man has no place to lay his head." - Jesus
      </h2>
    </div>
  </h1> 
</div>

<div class="clear"></div>
<br />

<div class="mission-statement booyah-box text-center col-10 offset-1">
  <h1>Mission Statement</h1>
  <br />
  <p>"I am for doing good to the poor, but I differ in opinion about the means. 
    I think the best way of doing good to the poor is not making them easy in poverty, but leading or driving them out of it." - Benjamin Franklin
  <br />
  <br />
    This best sums my intention for this website.  Drug and alcohol addiction is rampant in the homeless community.  This website is for homeless people and those living in poverty who will not squander the good intentions of others in order to feed their addictions.  
    While giving to those in need is good, resolving the issue entirely is the approach that I encourage people to take.  The goal of this
    operation is to permanently solve the issue of homelessness and poverty for those who truly hope and strive to better their life.  
  </p>
</div>

<script type="text/javascript">
  // Define a random integer function
  function random( n ){
    return Math.floor( Math.random() * n );
  }

  // Define some variables, hide all images and show just one of them.
  var transition_time = 1000;
  var waiting_time = 7000;
  var images = $('div#Slogan div');
  var n = images.length;
  var current = random( n );
  images.hide();
  images.eq( current ).show();

  // Periodically, we fadeOut the current image and fadeIn a random one
  var interval_id = setInterval( function(){
      images.eq( current ).fadeOut( transition_time, function(){
          current = random( n );
          images.eq( current ).fadeIn( transition_time );
      } );
  }, 2 * transition_time + waiting_time);
</script>

<br />
<br />

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 id="myModalLabel">Create A Profile</h4>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div class='col-5 offset-1 text-center'>
              <%= link_to("Give Help", new_helper_path, class: "btn btn-primary different-color-button btn-lg") %>
            </div>
            <div class='col-5 offset-1 text-center'> 
              <%= link_to("Get Help", new_helpee_path, class: "btn btn-primary different-color-button btn-lg") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="col-10 offset-1 text-center index-heading">
  <h1>Current members of our community</h1>
</div>

<br />

<div class="container">
  <div class="row">
    <div class="col-6">
      <div class="text-center">
        <h2>Who is helping others</h2>
      </div>
      
      <br />

      <% if @helper.present? %>
        <% @helper.each do |helper| %>
          <div class="booyah-box2">
            <div class="row">
              <div class="col-6">
                <% if helper.avatar.present? %>
                  <%= image_tag helper.avatar, class: "image-index" %>
                <% else %>
                  <%= image_tag "fillerProfile.jpg", class: "image-index" %>
                <% end %>
              </div>
              <div class="col-6 index-name">
                <h1 class="index-text"><%= link_to helper.name, helper_path(helper) %></h1>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-6">
      <div class="text-center">
        <h2>Who needs help?</h2>
      </div>
      <br />

      <% if @helpee.present? %>
        <% @helpee.each do |helpee| %>
          <div class="booyah-box2">
            <div class="row">
              <div class="col-6">
                <% if helpee.avatar.present? %>
                  <%= image_tag helpee.avatar, class: "image-index" %>
                <% else %>
                  <%= image_tag "fillerProfile.jpg", class: "image-index" %>
                <% end %>
              </div>
              <div class="col-6 index-name">
                <h1 class="index-text"><%= link_to helpee.name, helpee_path(helpee) %></h1>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>





  

app/views/places/resources.html.erb
<div id="map"></div>

<br />
<br />
  
<div class="booyah-box col-10 offset-1">
  <%= image_tag "bridge_house.jpg", class: 'img-fluid left' %>
  <h1>Bridge House</h1>
  <span id="marker0" class="markerclass on-hover">see map</span>
  <h3 class="underline-words">About</h3>
  <p>Bridge House plays a crucial role addressing homelessness. Not only do they provide outreach case management services for basic needs-from bus fare to prescription medications- they also provide employment services and nightly meals at our Community Table dinner program. Bridge House is a bridge for many seeking a pathway out of homelessness.</p>
  <p>Breakfast served every weekday at 9am.</p>
</div>

<div class="booyah-box col-10 offset-1">
  <%= image_tag "boulderhomelessshelter.jpg", class: 'img-fluid left' %>
  <h1>Boulder Shelter for the Homeless</h1>
  <span id="marker1" class="markerclass on-hover">see map</span>
  <h3 class="underline-words">About</h3>
  <p>Boulder Shelter for the Homeless provides safe shelter, food, and support services for homeless adults year around.  Morning Services, which includes breakfast, showers, access to laundry facilities, storage, mail, phone, and messages, are available from 6am until 8am, seven days a week, year-round to those not staying overnight at the Shelter.</p>
</div>

<div class="booyah-box col-10 offset-1">
  <%= image_tag "youth_shelter.jpg", class: 'img-fluid left' %>
  <h1>The Source - Boulder Youth Shelter</h1>
  <span id="marker2" class="markerclass on-hover">see map</span>
  <h3 class="underline-words">About</h3>
  <p>If you’re 12 to 24 years old and need help, Attention Homes is there for you. They offer shelter, food, clothing, counseling, education programs, health care, transportation assistance, and more. Their team of caring, experienced counselors and volunteers are trained to help you in every way possible.</p>
</div>

<div class="booyah-box col-10 offset-1" id="clickthis">
  <%= image_tag "efaa.jpg", class: 'img-fluid left' %>
  <h1>EFAA</h1>
  <span id="marker3" class="markerclass on-hover">see map</span>
  <h3 class="underline-words">About</h3>
  <p>Since 1918, EFAA has been the community safety net for families who have nowhere else to turn when they can’t meet their basic needs.</p>
  <p>EFAA Provides food and help with critical expenses, like rent, utilities, minor medical costs and transportation.</p>
</div>

<div class="booyah-box col-10 offset-1" id="clickthis">
  <%= image_tag "Boulder_county.jpg", class: 'img-fluid left' %>
  <h1>Boulder County Department of Housing and Human Services</h1>
  <span id="marker4" class="markerclass on-hover">see map</span>
  <h3 class="underline-words">About</h3>
  <p>Food stamps, TANF, Medicaid, countywide rental assistance, public housing and housing support services to low-income families, seniors, veterans and people with disabilities. Child welfare services, family driven intervention and prevention services for families in crisis, foster care and adoption services.</p>
</div>

<div class="booyah-box col-10 offset-1" id="clickthis">
  <%= image_tag "FPC.jpg", class: 'img-fluid left' %>
  <h1>Deacon’s Closet</h1>
  <span id="marker5" class="markerclass on-hover">see map</span>
  <h3 class="underline-words">About</h3>
  <p>Free clothing bank, 9.30-10.30am Thursdays.</p>
</div>

<div class="booyah-box col-10 offset-1" id="clickthis">
  <%= image_tag "HOH.jpg", class: 'img-fluid left' %>
  <h1>Harvest of Hope Food Pantry</h1>
  <span id="marker6" class="markerclass on-hover">see map</span>
  <h3 class="underline-words">About</h3>
  <p>Food pantry.</p>
</div>

<div class="booyah-box col-10 offset-1">
<h1>More Resources</h1>
<%= link_to "Community Resources", "https://bouldershelter.org/get-help/community-resources/" %>
<br />
<%= link_to "Resource Pamphlet", "https://bouldershelter.org/wp-content/uploads/2018/01/BSH-January-2018-Resource-Pamphlet.pdf" %>
</div>


<script>
  var marker = [];

    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 11,
        center: {lat: 40.0194747, lng: -105.28127790000002}
      });

      marker = [
        new google.maps.Marker({
          position: {lat: 40.0194747, lng: -105.28127790000002},
          map: map,
          title: 'Bridge House',
           content: '<p><a href="https://boulderbridgehouse.org/">'+
              '<b class="underline-words">Bridge House</b></a> ' + '<br />' + 'Address: 2691 30th St, Boulder, CO 80301' + '<br/>' +
              '(303) 442-8300' +'</p>' + '<p>' + '<b class="underline-words">Hours</b>' + '<br/>' + 'Monday 9AM–3PM' + '<br />' + 'Tuesday 9AM–3PM' + 
              '<br />' + 'Wednesday 9AM–3PM' + '<br />' + 'Thursday 9AM–3PM' + '<br />' + 'Friday 9AM–3PM' + '<br />' +
              'Saturday CLOSED' + '<br />' + 'Sunday CLOSED' + '</p>'
        }),

        new google.maps.Marker({
          position: {lat: 40.062568, lng: -105.282617},
          map: map,
          title: 'Boulder Shelter The Homeless',
          content: '<p><a href="https://bouldershelter.org/">'+
              '<b class="underline-words">Boulder Shelter The Homeless</b></a> ' + '<br />' + '4869 Broadway St, Boulder, CO 80304' + 
              '<br/>' + '303-442-4646' +'</p>' + '<p>' + '<b class="underline-words">Hours</b>' + '<br/>' + 'Monday 5PM-10AM' + 
              '<br />' + 'Tuesday 5PM-10AM' + '<br />' + 'Wednesday 5PM-10AM' + '<br />' + 'Thursday 5PM-10AM' + '<br />' + 'Friday 5PM-10AM' + 
              '<br />' + 'Saturday 5PM-10AM' + '<br />' + 'Sunday 5PM-10AM' + '</p>'
        }),

        new google.maps.Marker({
          position: {lat: 40.030667, lng: -105.281725},
          map: map,
          title: 'The Source - Boulder Youth Shelter',
          content: '<p><a href="https://www.attentionhomes.org/thesource/">'+
              '<b class="underline-words">The Source - Boulder Youth Shelter</b></a> ' + '<br />' + '3080 Broadway, Boulder, CO 80304' + 
              '<br/>' + '(303) 447-1207' +'</p>' + '<p>' + '<b class="underline-words">Hours</b>' + '<br/>' + '24/7' + '</p>'
        }),

        new google.maps.Marker({
          position: {lat: 40.058472, lng: -105.277706},
          map: map,
          title: 'EFAA',
          content: '<p><a href="https://www.efaa.org/">'+
              '<b class="underline-words">EFAA</b></a> ' + '<br />' + '1575 Yarmouth Ave Boulder, CO 80304' + 
              '<br/>' + '303-442-3042' +'</p>' + '<p>' + '<b class="underline-words">Hours</b>' + '<br/>' + 'Monday 9:30AM-4:30PM' + 
              '<br />' + 'Tuesday 9:30AM-4:30PM' + '<br />' + 'Wednesday 12PM-4:30PM' + '<br />' + 'Thursday 9:30AM-6PM' + '<br />' + 'Friday 9:30AM-4:30PM' + 
              '<br />' + 'Saturday CLOSED' + '<br />' + 'Sunday CLOSED' + '</p>'
        }),

        new google.maps.Marker({
          position: {lat: 40.036709, lng: -105.281953},
          map: map,
          title: 'Boulder County Department of Housing and Human Services',
           content: '<p><a href="https://www.bouldercounty.org/departments/housing-and-human-services/">'+
              '<b class="underline-words">Boulder County Department of Housing and Human Services</b></a> ' + '<br />' + 'Address: 3400 Broadway, Boulder, CO 80304' + '<br/>' +
              '(303) 441-1000' +'</p>' + '<p>' + '<b class="underline-words">Hours</b>' + '<br/>' + 'Monday 8AM–4:30PM' + '<br />' + 'Tuesday 8AM–4:30PM' + 
              '<br />' + 'Wednesday 8AM–4:30PM' + '<br />' + 'Thursday 8AM–4:30PM' + '<br />' + 'Friday 8AM–4:30PM' + '<br />' +
              'Saturday CLOSED' + '<br />' + 'Sunday CLOSED' + '</p>'
        }),

        new google.maps.Marker({
          position: {lat: 40.018239, lng: -105.274112},
          map: map,
          title: 'Deacon’s Closet',
           content: '<p><a href="https://www.fpcboulder.org/deacons">'+
              '<b class="underline-words">Deacon’s Closet</b></a> ' + '<br />' + 'Address: 1603 Walnut Street, Boulder, CO 80302' + '<br/>' +
              '(303) 402-6400' +'</p>' + '<p>' + '<b class="underline-words">Hours</b>' + '<br/>' + 'Thursday 9:30AM–10:30AM' + '</p>'
        }),

        new google.maps.Marker({
          position: {lat: 40.028736, lng: -105.254545},
          map: map,
          title: 'Harvest of Hope Food Pantry',
           content: '<p><a href="http://hopepantry.org/">'+
              '<b class="underline-words">Harvest of Hope Food Pantry</b></a> ' + '<br />' + 'Address: 2960 Valmont Road, Boulder, CO 80302' 
              + '<br/>' +'(720) 382-1971' +'</p>' + '<p>' + '<b class="underline-words">Hours</b>' + '<br/>' + 'Monday 9AM–11AM, 12PM-2PM' 
              + '<br />' 
              + 'Tuesday 9AM–11AM, 12PM-2PM' + '<br />' + 'Wednesday 9AM–11AM, 12PM-2PM' + '<br />' + 'Thursday 9AM–11AM, 12PM-2PM' +
               '<br />' + 'Friday 9AM–11AM, 12PM-2PM' + '<br />' +
              'Saturday CLOSED' + '<br />' + 'Sunday CLOSED' + '</p>'
        })
      ];      

      var infowindow = new google.maps.InfoWindow();

      marker.forEach (function(marker){
        google.maps.event.addListener(marker, 'click', (function(marker) {
          return function() {
            infowindow.setContent(marker.content);
            infowindow.open(map, marker);
          }
        })(marker))
      });
    }

    // Deleted turbolinks because of conflict with chatrooms.
    // $(document).on("turbolinks:load", function(){
    $(document).on('ready page:load', function () {
      $(".markerclass").click(function(e) {
        e.preventDefault();
        var markerid = $(this).attr("id").replace("marker", "")
        myClick(markerid);
      });
    });

    function myClick(id){
      $('html, body').animate({ scrollTop: $('#map').offset().top }, 'slow');
      google.maps.event.trigger(marker[id], 'click');
    }

</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwy0zq-PsBe_jtUVPkba-Jkm09YsXXvmg&callback=initMap">
</script>


  